version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '88:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: arm64v8/mongo
    ports:
      - '27017:27017'
